### ISSUE TITLE
Parse JSON instead of scrape DOM?

### ISSUE THREAD

**Issue by frdmn** [norm/snapmatic#3]
Just found this JSON endpoint: 

```
http://de.socialclub.rockstargames.com/member/restlessnarwhal/games/gtav/snapmatic/ajax/search?page=0
```

Pro:
- you can get ALL snapmatic pics, because we have access to the pagination
- probably easier to parse

Con:
- ~~You need the Xuid of the specific GamerTag that you want to lookup.~~  
  (you dont, since you can just adjust the gamertag in the url above like this:) 

```
http://de.socialclub.rockstargames.com/member/rnarian/games/gtav/snapmatic/ajax/search?page=0
```

Just an idea :)

**Comment by norm** [comment]
Closing this as out of date — that feed only seems to return data when authenticated to Social Club. The script is updated now to login and fetch the pictures using the general ajax endpoint. 

(Sorry @frdmn for ignoring it for so long, I'd stopped playing GTA)

**Comment by frdmn** [comment]
No worries!

:+1:
